name: Build and Deploy LaTeX PDF

on:
  push:
    paths:
      - 'resume.tex'
  pull_request:
    paths:
      - 'resume.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

      - name: Compile LaTeX document
        run: pdflatex resume.tex

      - name: Move PDF to deploy folder
        run: |
          mkdir public
          mv resume.pdf public/

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: public/resume.pdf

      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
